name: qq
channels: 
  - huggingface
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - datasets=2.10.1
  # - datasets=2.8.0
  # - datasets=1.5.0
  - pytorch-gpu=1.12.1
  - cudatoolkit=11.5
  - pandas
  - numpy
  - tqdm
  - pip
  - huggingface_hub=0.10.1
  - sentencepiece
  - joblib
  - urllib3
  - ujson
  # BigBird (vasudevgupta)
  - jsonlines=3.1.0
  - openssl=1.1.1
  # matt
  - ipykernel
  - black
  - click
  - tensorboard
  - scikit-learn>=1.2.0
  - openai
  - nltk
  - pytables=3.7.0 # df.to_hdf()
  - fire
  # - h5py
  - pip:
    # - transformers==4.21.3 # Later versions fail during distributed training
    - transformers==4.28.1 # new version which include tokenizer for alpaca
    # BigBird (vasudevgupta)
    - apache-beam