name: qq
channels: 
  - huggingface
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - datasets=2.6.1
  - pytorch-gpu=1.12.1
  - cudatoolkit=11.5
  - pandas=1.4.3
  - numpy=1.23.1
  - tqdm=4.64.0
  - pip=22.1.2
  - huggingface_hub=0.10.1
  - sentencepiece=0.1.95
  - joblib=1.1.1
  - urllib3=1.26.11
  # BigBird (vasudevgupta)
  - jsonlines=3.1.0
  # AISO
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - fuzzysearch=0.7.3
  - python-levenshtein=
  - elasticsearch
  - redis
  - regex
  - ujson
  - pexpect
  - prettytable>=2.0.0
  - faiss
  # matt
  - ipykernel
  - black
  - pip:
    - transformers==4.24.0
    # BigBird (vasudevgupta)
    - apache-beam