name: qq
channels: 
  - huggingface
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - datasets=1.5.0
  - pytorch-gpu=1.12.1
  - cudatoolkit=11.5
  - pandas
  - numpy
  - tqdm
  - pip
  - huggingface_hub=0.10.1
  - sentencepiece
  - joblib
  - urllib3
  # BigBird (vasudevgupta)
  - jsonlines=3.1.0
  - openssl=1.1.1
  # AISO
  # - scipy=1.9.3
  # - scikit-learn=1.1.3
  # - fuzzysearch=0.7.3
  # - python-levenshtein=
  # - elasticsearch
  # - redis
  # - regex
  # - ujson
  # - pexpect
  # - prettytable>=2.0.0
  # - faiss
  # matt
  - ipykernel
  - black
  - click
  - tensorboard
  - pip:
    - transformers==4.21.3 # Later versions fail during distributed training
    # BigBird (vasudevgupta)
    - apache-beam