# name: qq2
# channels: 
#   - huggingface
#   - conda-forge
#   - anaconda
# dependencies:
#   - python=3.8
#   - datasets=2.10.1
#   # - datasets=2.8.0
#   # - datasets=1.5.0
#   - pytorch-gpu=1.12.1
#   - cudatoolkit=11.5
#   - pandas
#   - numpy
#   - tqdm
#   - pip
#   - ujson

#   # matt
#   - ipykernel
#   - black
#   - click
#   - tensorboard
#   - scikit-learn>=1.2.0
#   - openai
#   - nltk
#   # - pytables=3.7.0 # df.to_hdf()
#   - xlwt # df.to_xls()
#   # - h5py
#   - fire
#   - openai

#   # alpaca training
#   - peft
#   - bitsandbytes
#   - trl
  
#   - pip:
#     - transformers==4.28.1 # new version which include tokenizer for alpaca
